In [5]:
from icecream import ic

In [2]:
arr = [1,2,3]

print( arr * 5 )

arr = [ x*5 for x in arr] 

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [49]:
import numpy as np 

arr1 = np.array([1,2,3,4,5] )



print(arr1)

[1 2 3 4 5]


In [11]:
from icecream import ic


arr = np.random.rand(2,3)
ic(arr) 
ic(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
ic(arr.size)

ic| arr: array([[0.37481001, 0.88834416, 0.22954971],
                [0.74081299, 0.79133535, 0.76163862]])
ic| type(arr): <class 'numpy.ndarray'>
ic| arr.size: 6


float64
(2, 3)
2


6

In [13]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (2,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[8 9 6]
 [1 3 1]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [14]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[57.1285726  92.96132427 93.53477516 76.84271418]
  [61.28312236 57.42341339 72.14995632 58.2281771 ]
  [63.31486369 60.50911837 63.26130327 91.89122536]]

 [[76.0423463  98.67250076 68.96949068 80.53231296]
  [81.53936896 83.32125763 71.78509016 63.30446868]
  [66.21789594 92.18654434 81.74830513 51.8854476 ]]

 [[69.72009743 54.17586382 53.92052012 60.01154433]
  [61.62568424 97.98483576 60.53137024 74.21430021]
  [77.92948337 85.65880118 74.69612694 84.75903459]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


## array creation with range functions

In [22]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 ).reshape(3,3) 
 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [23]:
# np.linspace(start , end(included) , koita) 

arr = np.linspace(0, 4 ,6)


print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [29]:
# np.logspace(start , end(included) , koita ) 

arr = np.logspace(0 , 4 ,6,base=2) 

print(arr)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


## creating matrix for Linear algebra

In [30]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [32]:
# identity matrix 

identity_mat = np.eye(3)
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [34]:

# np.eye(row , column,k) 

mat = np.eye(3,4,-1)
print(mat)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [36]:
mat = np.eye(3,4,1)
print(mat)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## indexing and slicing

In [38]:

# 2d array 
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

In [41]:
#indexing 

print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [42]:
print(arr[2])

3.0314331330207964


In [50]:
arr1[2]= 100
print(arr1)

[  1   2 100   4   5]


In [46]:
print(arr2[0][1])

2


In [51]:
arr1_mod = arr1[1:4].copy()
print(arr1_mod)

[  2 100   4]


In [53]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]

print(arr2) 

[[1 2 3]
 [4 5 6]]


In [54]:
row0 = arr2[0:1,]
print(row0)

[[1 2 3]]


In [55]:
row1 = arr2[1: ,]
print(row1)

[[4 5 6]]


In [60]:
col0 = arr2[ ::,0:1]
print(col0)

[[1]
 [4]]


In [62]:
col2 = arr2[ ::,1:2]
print(col2)

[[2]
 [5]]


In [63]:
#getting a portion 


portion = arr2[:: , 0:2] 
print(portion)

[[1 2]
 [4 5]]


## Advanced Indexing

In [66]:
print(arr2)
print(arr2[[0,1] , [1,2]])


[[1 2 3]
 [4 5 6]]
[2 6]


In [67]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr>1])
arr2[arr2>2] = 0 

print(arr2)

[[1 2 3]
 [4 5 6]]
[2 6]


IndexError: boolean index did not match indexed array along axis 0; size of axis is 2 but size of corresponding boolean axis is 6