In [2]:
import numpy as np

# 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [3]:
# 1D array
array_1d = np.array([1,2,3,4,5])

In [6]:
print(array_1d)
print(array_1d.ndim)
print(array_1d.shape)

[1 2 3 4 5]
1
(5,)


In [8]:
# 2D array 
array_2d = np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
print(array_2d)
print(array_2d.ndim)
print(array_2d.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [11]:
# 3D array 
array_3d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [14]:
print(array_3d)
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8


# 2 . Create:
an array of zeros of shape (3,3)


an array of ones of shape (2,5)


an array filled with 7


In [15]:
zero_array = np.zeros((3,3))

In [16]:
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
ones_array = np.ones((2,5))

In [20]:
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
sevens_array = np.full((3,3),7)

In [22]:
print(sevens_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# 3 . Create an array of even numbers between 10 and 50 using arange.

In [23]:
even_array = np.arange(10,51,2)

In [24]:
print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


# 4 . Create a 4×4 matrix from 0–15. Then , extract:
the first row


the last column


a 2×2 subarray from the center


In [25]:
# Create a 4x4 matrix with numbers from 0 to 15
matrix = np.arange(16).reshape(4,4)

In [26]:
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [27]:
first_row = matrix[0, :]

In [30]:
print(first_row)

[0 1 2 3]


In [35]:
last_col = matrix[:,-1]

In [36]:
print(last_col)

[ 3  7 11 15]


In [37]:
center_subarray = matrix[1:3, 1:3]

In [38]:
print(center_subarray)

[[ 5  6]
 [ 9 10]]


# 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [43]:
matrix = np.arange(9).reshape(3,3)
array_1d = np.array([1,2,3])
reault = matrix + array_1d

In [45]:
print(matrix)
print(array_1d)
print(reault)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


# 6 . Given two arrays A and B, compute:
(A + B) / 2


A**2 + B**2


In [52]:
a = np.array([1,2,3])
b= np.array([4,5,6])
reasult1 = (a+b)/2

In [53]:
print(reasult1)

[2.5 3.5 4.5]


In [55]:
# Compute a^2 + b^2
result2 = a**2 + b**2
print(result2)

[17 29 45]
