In [1]:
import numpy as np

In [2]:
import pandas as pd

1. Student Marks Analyzer
You are helping a teacher check exam results.
 Create a NumPy array with 10 random integers between 0 and 100 (student scores).

 Find:
 - the highest score
 - the lowest score
 - the average score

 Hint: use np.random.randint(), arr.max(), arr.min(), arr.mean()

In [11]:
scores = np.random.randint(0,101, size=10)

In [12]:
print(scores)
print(f" highest: {scores.max()}")
print(f" lowest : {scores.min()}")
print(f" avg: {scores.mean()}")

[99 28 54 51 77 60 30 38 21 70]
 highest: 99
 lowest : 21
 avg: 52.8


2. Warehouse Weights
A warehouse stores item weights (in kg):
 arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

 Find and print:
 - all items heavier than 50 kg
 - the sorted weights
 - the index of the heaviest item

 Hint: use arr[arr > 50], np.sort(arr), arr.argmax()

In [21]:
arr = np.array([45, 60, 55, 30, 90, 75, 40, 50])

In [22]:
heavier = arr[arr > 50]
sorted_weights = np.sort(arr)

In [24]:
heaviest_index = arr.argmax()

In [26]:
print(arr)
print("Items > 50 kg:", heavier)
print("Sorted Weights:", sorted_weights)
print("Index of Heaviest Item:", heaviest_index)

[45 60 55 30 90 75 40 50]
Items > 50 kg: [60 55 90 75]
Sorted Weights: [30 40 45 50 55 60 75 90]
Index of Heaviest Item: 4


3. Temperature Report
A weather station collects temperatures (°C) from 4 zones.
 Generate random integers between 20 and 40 for a 4×4 grid.

 Then find:
 - the average temperature of each zone (row)
 - the highest temperature in the grid
 - replace all temperatures above 35 with 35

In [42]:
# 4x4 grid of random temps between 20 and 40
temps = np.random.randint(20, 41, size=(4, 4))

# Average temp per zone (row)
avg_per_zone = temps.mean(axis=1)

# Highest temperature in the grid
max_temp = temps.max()

# Replace temps > 35 with 35
temps_capped = np.where(temps > 35, 35, temps)

print("Temperature Grid:", temps)
print("Average per Zone:", avg_per_zone)
print("Max Temperature:", max_temp)
print("Capped Temperatures (max 35):", temps_capped)

Temperature Grid: [[21 36 27 32]
 [22 20 40 30]
 [34 34 22 35]
 [32 33 23 30]]
Average per Zone: [29.   28.   31.25 29.5 ]
Max Temperature: 40
Capped Temperatures (max 35): [[21 35 27 32]
 [22 20 35 30]
 [34 34 22 35]
 [32 33 23 30]]


4. Traffic Data
A city records the number of cars passing 5 intersections in 3 time slots (morning, afternoon, night).
 Create a 3×5 array of random integers between 0 and 50.

 Then find:
 - total cars per intersection (sum by column)
 - total cars per time slot (sum by row)

In [43]:
# 3 time slots (rows) x 5 intersections (columns)
traffic = np.random.randint(0, 51, size=(3, 5))

# Total cars per intersection (sum across rows → by column)
total_per_intersection = traffic.sum(axis=0)

# Total cars per time slot (sum across columns → by row)
total_per_timeslot = traffic.sum(axis=1)

print("Traffic Data:", traffic)
print("Total Cars per Intersection:", total_per_intersection)
print("Total Cars per Time Slot:", total_per_timeslot)

Traffic Data: [[31  1  0  5 24]
 [40 12 48 30 40]
 [ 8 22 49  5 13]]
Total Cars per Intersection: [79 35 97 40 77]
Total Cars per Time Slot: [ 61 170  97]


5. Fruit Store Stock
You sell fruits in your store. Stock levels (kg) for 5 days are:
 stock = np.array([12, 15, 9, 20, 18])

 A new delivery adds 5 kg to each stock.
 Then 10% of all fruits get spoiled.

 Find the final stock levels.

 Hint: use broadcasting and simple math.

In [44]:
stock = np.array([12, 15, 9, 20, 18])

# Add 5 kg to each
stock += 5

# 10% spoilage
stock *= 0.9  # or stock = stock * 0.9

print("Final Stock Levels (kg):", stock)

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

## Part 2: Pandas Practice

1. Student Report Analyzer
You are given this data:

 import pandas as pd

 data = {
 	'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
 	'Math': [88, 75, 95, 60, 80],
 	'English': [78, 85, 90, 70, 88],
 	'Science': [92, 70, 85, 65, 90]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Display only the first 3 rows.
 2. Print the column names and index values.

In [45]:
data = {
    'Name': ['Rahim', 'Karim', 'Selina', 'Babul', 'Mitu'],
    'Math': [88, 75, 95, 60, 80],
    'English': [78, 85, 90, 70, 88],
    'Science': [92, 70, 85, 65, 90]
}
df = pd.DataFrame(data)

# 1. First 3 rows
print("First 3 Rows:")
print(df.head(3))

# 2. Column names and index
print("\nColumn Names:", df.columns.tolist())
print("Index Values:", df.index.tolist())

First 3 Rows:
     Name  Math  English  Science
0   Rahim    88       78       92
1   Karim    75       85       70
2  Selina    95       90       85

Column Names: ['Name', 'Math', 'English', 'Science']
Index Values: [0, 1, 2, 3, 4]


2. Shop Sales Data
You run a small electronics shop. The data is stored like this:

 data = {
 	'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
 	'Price': [700, 1200, 300, 250, 50],
 	'Units_Sold': [10, 5, 8, 6, 20]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Display only the 'Product' and 'Price' columns.
 2. Access the 3rd row using both iloc and loc.
 3. Show the top 3 products with the highest revenue.

In [46]:
data = {
    'Product': ['Phone', 'Laptop', 'Tablet', 'Monitor', 'Mouse'],
    'Price': [700, 1200, 300, 250, 50],
    'Units_Sold': [10, 5, 8, 6, 20]
}
df = pd.DataFrame(data)

# 1. Product and Price columns
print("Product & Price:")
print(df[['Product', 'Price']])

# 2. 3rd row using iloc and loc
print("\n3rd Row (iloc):", df.iloc[2])
print("3rd Row (loc):", df.loc[2])  # Only works if index is default (0,1,2...)

# 3. Top 3 products by revenue (Price * Units_Sold)
df['Revenue'] = df['Price'] * df['Units_Sold']
top3 = df.nlargest(3, 'Revenue')
print("\nTop 3 Products by Revenue:")
print(top3[['Product', 'Revenue']])

Product & Price:
   Product  Price
0    Phone    700
1   Laptop   1200
2   Tablet    300
3  Monitor    250
4    Mouse     50

3rd Row (iloc): Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object
3rd Row (loc): Product       Tablet
Price            300
Units_Sold         8
Name: 2, dtype: object

Top 3 Products by Revenue:
  Product  Revenue
0   Phone     7000
1  Laptop     6000
2  Tablet     2400


3. Attendance Tracker
Here’s an attendance sheet:

 data = {
 	'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
 	'Days_Present': [20, 18, 22, 15, 25],
 	'Days_Absent': [2, 4, 1, 7, 0]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Make 'Student' the index column.
 2. Drop the 'Days_Absent' column.

In [47]:
data = {
    'Student': ['Amin', 'Tina', 'Rafi', 'Nadia', 'Sabbir'],
    'Days_Present': [20, 18, 22, 15, 25],
    'Days_Absent': [2, 4, 1, 7, 0]
}
df = pd.DataFrame(data)

# 1. Set 'Student' as index
df.set_index('Student', inplace=True)
print("DataFrame with Student as Index:")
print(df)

# 2. Drop 'Days_Absent' column
df.drop(columns=['Days_Absent'], inplace=True)
print("\nAfter dropping Days_Absent:")
print(df)

DataFrame with Student as Index:
         Days_Present  Days_Absent
Student                           
Amin               20            2
Tina               18            4
Rafi               22            1
Nadia              15            7
Sabbir             25            0

After dropping Days_Absent:
         Days_Present
Student              
Amin               20
Tina               18
Rafi               22
Nadia              15
Sabbir             25


4. Filtering Employee Data
Employee record:

 data = {
 	'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
 	'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
 	'Salary': [40000, 55000, 52000, 45000, 47000],
 	'Experience': [2, 5, 4, 3, 6]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show employees with Salary > 45000.
 2. Show employees from the IT department only.
 3. Show employees with Salary > 45000 and Experience > 3.
 4. Sort the employees by Experience (ascending).

In [48]:
data = {
    'Name': ['Rafiq', 'Nadia', 'Tuhin', 'Rima', 'Faruk'],
    'Department': ['HR', 'IT', 'IT', 'Sales', 'Sales'],
    'Salary': [40000, 55000, 52000, 45000, 47000],
    'Experience': [2, 5, 4, 3, 6]
}
df = pd.DataFrame(data)

# 1. Salary > 45000
print("Salary > 45000:")
print(df[df['Salary'] > 45000])

# 2. IT Department only
print("\nIT Department:")
print(df[df['Department'] == 'IT'])

# 3. Salary > 45000 AND Experience > 3
print("\nSalary > 45000 and Experience > 3:")
print(df[(df['Salary'] > 45000) & (df['Experience'] > 3)])

# 4. Sort by Experience (ascending)
print("\nSorted by Experience (asc):")
print(df.sort_values(by='Experience'))

Salary > 45000:
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

IT Department:
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4

Salary > 45000 and Experience > 3:
    Name Department  Salary  Experience
1  Nadia         IT   55000           5
2  Tuhin         IT   52000           4
4  Faruk      Sales   47000           6

Sorted by Experience (asc):
    Name Department  Salary  Experience
0  Rafiq         HR   40000           2
3   Rima      Sales   45000           3
2  Tuhin         IT   52000           4
1  Nadia         IT   55000           5
4  Faruk      Sales   47000           6


5. City Weather Dashboard
data = {
 	'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
 	'Temp': [32, 28, 30, 35, 33],
 	'Humidity': [60, 75, 70, 55, 65]
 }
 df = pd.DataFrame(data)

 Tasks:
 1. Show only the cities where FeelsLike > 33.
 2. Sort the DataFrame by FeelsLike (descending).
 3. Find which city has the highest humidity.

In [49]:
data = {
    'City': ['Dhaka', 'Sylhet', 'Chittagong', 'Rajshahi', 'Khulna'],
    'Temp': [32, 28, 30, 35, 33],
    'Humidity': [60, 75, 70, 55, 65]
}
df = pd.DataFrame(data)

# 1. Cities where Temp > 33
print("Cities with Temp > 33:")
print(df[df['Temp'] > 33])

# 2. Sort by Temp (descending)
print("\nSorted by Temp (descending):")
print(df.sort_values(by='Temp', ascending=False))

# 3. City with highest Humidity
max_humidity_city = df.loc[df['Humidity'].idxmax(), 'City']
print("\nCity with Highest Humidity:", max_humidity_city)

Cities with Temp > 33:
       City  Temp  Humidity
3  Rajshahi    35        55

Sorted by Temp (descending):
         City  Temp  Humidity
3    Rajshahi    35        55
4      Khulna    33        65
0       Dhaka    32        60
2  Chittagong    30        70
1      Sylhet    28        75

City with Highest Humidity: Sylhet


In [ ]:
|